### ISSUE TITLE
Could you please share your detectron2 or your other packages versions?Thx

### ISSUE THREAD

**Issue by Ireliya** [ImNotPrepared/AirShot#2]
I just use detectron2 and your other package versions from your previous work: airdet, but when I run your codes it shows I missing some parts.
detectron2-0.2-py3.6-linux-x86_64.egg/detectron2/modeling/backbone/resnet.py", line 524, in make_stage
    return ResNet.make_stage(*args, **kwargs)
TypeError: make_stage() missing 1 required positional argument: 'first_stride'

**Comment by Z1hanW** [comment]
Hi, thx for ur interest. AirDet version should work.

We are using the v0.6 version as it is more stable. (v0.2 should also work) The error you encountered is a very common Internal compatibility issues (which happens both in v0.2 and v0.6, and to me back to when I started) which you can find solution [here](https://github.com/fanq15/FewX/issues/40#issuecomment-820984528) which requires you to revise the source file. Once you fix it, it should be ok to run.
